export const uiroutes = {
  DASHBOARD_ROUTE: 'dashboard',
  PROFILE_ROUTE: 'profile',
  ACCOUNT_ROUTE: 'account',
  SUPPORT_ROUTE: 'support',
  INSTITUTION_FORM_ROUTE: 'institution-form',
  MEMBER_FORM_ROUTE: 'member-form',
  MEMBER_PROFILE_ROUTE: 'member-profile',
  GROUP_FORM_ROUTE: 'group-form',
  GROUP_PROFILE_ROUTE: 'group',
  ANNOUNCEMENT_FORM_ROUTE: 'announcement-form',
  ANNOUNCEMENT_PROFILE_ROUTE: 'announcement',
  COURSE_FORM_ROUTE: 'course-form',
  COURSE_PAGE_ROUTE: 'course',
  ASSIGNMENT_FORM_ROUTE: 'assignment-form',
  ASSIGNMENT_PAGE_ROUTE: 'assignment',
};
