export const uiroutes = {
  ACTIVATE_ACCOUNT: 'activate',
  PASSWORD_RESET: 'password-reset',
  RESEND_ACTIVATION_EMAIL: 'resend-activatioin-email',
  DASHBOARD_ROUTE: 'dashboard',
  PROFILE_ROUTE: 'profile',
  ACCOUNT_ROUTE: 'account',
  SUPPORT_ROUTE: 'support',
  INSTITUTION_PROFILE_ROUTE: 'institution',
  INSTITUTION_FORM_ROUTE: 'institution-form',
  MEMBER_FORM_ROUTE: 'member-form',
  MEMBER_PROFILE_ROUTE: 'member-profile',
  USER_ROLE_FORM_ROUTE: 'user-role-form',
  USER_ROLE_PROFILE_ROUTE: 'user-role-profile',
  GROUP_FORM_ROUTE: 'group-form',
  GROUP_PROFILE_ROUTE: 'group',
  ANNOUNCEMENT_FORM_ROUTE: 'announcement-form',
  ANNOUNCEMENT_PROFILE_ROUTE: 'announcement',
  COURSE_FORM_ROUTE: 'course-form',
  COURSE_PROFILE_ROUTE: 'course',
  ASSIGNMENT_FORM_ROUTE: 'assignment-form',
  ASSIGNMENT_PROFILE_ROUTE: 'assignment',
  CHAT_ROUTE: 'chat',
};
